### PR TITLE
Update NFD image tag for RHOCP 4.13

### PR DESCRIPTION
**Pull request by hershpa**
Signed-off-by: Hersh Pathak hersh.pathak@intel.com

### CODE REVIEW

**Comment by hershpa** [comment]
@vbedida79 will we need this PR or for 0.28.0 bundle, this file is no longer needed?

**Comment by vbedida79** [comment]
> will we need this PR OR for 0.28.0 bundle, this file is no longer needed?

yeah, we need to check if it works with 0.28.0 bundle

**Comment by hershpa** [comment]
Great, thanks.

**Comment by vbedida79** [comment]
We would need this PR for 1.1.0 as we use sgx with init container for nfd epc resource. lgtm

**Comment by hershpa** [comment]
Thanks @vbedida79!

**Comment by uMartinXu** [comment]
it looks good to me.

**Pull request merged**
