### PR TITLE
machine_config: Add steps to verify QAT machine configuration

### PR DESCRIPTION
**Pull request by hershpa**
Signed-off-by: Hersh Pathak hersh.pathak@intel.com

### CODE REVIEW

**Review by vbedida79 — APPROVED** [review]

**Comment by hershpa** [comment]
Thanks @vbedida79 for the quick review!

**Comment by hershpa** [comment]
Is this good and ready to merge? Thanks!

**Comment by hershpa** [comment]
Following up.

**Comment by hershpa** [comment]
One more bump to check if this PR is ready to go. Thanks!

**Comment by uMartinXu** [comment]
It looks good to me.

**Pull request merged**
