### PR TITLE
workflows: Delete workflow as it is no longer used

### PR DESCRIPTION
**Pull request by hershpa**
Signed-off-by: Hersh Pathak hersh.pathak@intel.com

### CODE REVIEW

**Review by uMartinXu — COMMENTED** [review]
Could you add more information why we need to disable workflow trigger on pull_request?

**Comment by hershpa** [comment]
This workflow is no longer being used. It currently runs whenever a PR is opened. As a result, we are disabling it.

**Comment by hershpa** [comment]
Updated the PR to delete the unused workflow

**Comment by chaitanya1731** [comment]
Looks good to me... We can remove this workflow as this was added to test any functionality for OCP changes using PR.. Since we no longer have the runner and we are not using this workflow, we can remove it.

**Review by chaitanya1731 — APPROVED** [review]

**Review by uMartinXu — APPROVED** [review]

**Pull request merged**
