### PR TITLE
QAT: remove c6xxx and fix maxNumDevices

### PR DESCRIPTION
**Pull request by mregmi**
Since We only support 4xxx qat devices, remove unsupported device. Set maxNumDevices to 128.
Signed-off-by: Manish Regmi <manish.regmi@intel.com>

### CODE REVIEW

**Review by mythi — APPROVED** [review]

**Comment by uMartinXu** [comment]
How do we let our customers know what is 4xxx? what is C6XXX? And how to figure out the QAT device type they are using?

**Comment by mregmi** [comment]
> How do we let our customers know what is 4xxx? what is C6XXX? And how to figure out the QAT device type they are using?

I will add a line in README about QAT hardware versions. We only support only one version for now 4xxx

**Comment by hershpa** [comment]
From my understanding, 4xxxx refers to 4th Gen Intel Xeon processors (Sapphire Rapids) and QATlib only supports 4xxxx as well.

**Comment by mythi** [comment]
It's not ok to say we only support 4xxx. All in-tree drivers are expected to work but only 4xxx is validated as part of the certification.

**Comment by mythi** [comment]
> How do we let our customers know what is 4xxx? what is C6XXX? And how to figure out the QAT device type they are using? 

Use appropriate NodeFeatureRules setting for the desired QAT PCI ID values

**Comment by hershpa** [comment]
@chaitanya1731 can you take a look at this one and ensure the image path is correct?

**Comment by hershpa** [comment]
This one should be ready to merge?

**Comment by chaitanya1731** [comment]
@hershpa the 4xxx and maxNumDevices changes looks good.. But I still see the container images SHAs are updated too as a part of this PR as these are already merged.. can you take a look?

**Comment by hershpa** [comment]
> @hershpa the 4xxx and maxNumDevices changes looks good.. But I still see the container images SHAs are updated too as a part of this PR as these are already merged.. can you take a look?

Done!

**Comment by chaitanya1731** [comment]
Thanks @mregmi and @hershpa. @uMartinXu this looks good now.

**Comment by hershpa** [comment]
Great!

**Comment by uMartinXu** [comment]
This PR looks good to me.

**Pull request merged**
